-- 1. The Revision Info table MUST come before the Audit table
-- We use "revinfo" to match Hibernate's default legacy Envers name
CREATE SEQUENCE revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- 2. The Main Transaction Table
CREATE TABLE transactions (
    id UUID PRIMARY KEY,
    transaction_reference VARCHAR(255) UNIQUE NOT NULL,
    source_account_id VARCHAR(255) NOT NULL,
    destination_account_id VARCHAR(255) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(50),
    transaction_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version INTEGER
);

-- 3. The Audit Table
-- Note: revtype is 0 (ADD), 1 (MOD), or 2 (DEL)
CREATE TABLE transactions_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    transaction_reference VARCHAR(255),
    source_account_id VARCHAR(255),
    destination_account_id VARCHAR(255),
    amount DECIMAL(19, 4),
    currency VARCHAR(3),
    status VARCHAR(50),
    transaction_type VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_transaction_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);